### PR TITLE
updated version with working PyPi requirements

### PR DESCRIPTION
**Pull request by serverhorror**
Hi,

referring to http://github.com/dinoboff/github-tools/issues/#issue/19

This pull request should apply cleanly to mastser. The PyPi version is increased plus hopefully everything added (README, CHANGES, ...) that should be there. Based on: http://github.com/mdornseif/github-tools/commit/a35be1ed26fcafc643c64d86e3ead6e099985ad7 which actually fixes the requirements...

(Sorry couldn't help myself I just hate trailing whitespace, but at least I made the commit obvious) :)
http://github.com/serverhorror/github-tools/commit/583d919806ea022a0cc49d9be218426190b0cc7c

### CODE REVIEW

**Comment by serverhorror** [comment]
_bump_ Any comments on the changes?

**Comment by mattions** [comment]
This would be cool, although the latest version of GitPython is 0.3.1
I'm wondering if does not make sense to bring everything up to date with the latest

**Comment by ponty** [comment]
To install updated version:

```
easy_install https://github.com/mdornseif/github-tools/zipball/master
```

**Comment by mattions** [comment]
Hello,

just wanted to say the last version proposed by ponty works properly and install without a fuss.
It should really be pulled into this repo as well.

**Comment by ponty** [comment]
Install is OK but I  can not use it for gh-pages.
I recommend using https://github.com/davisp/ghp-import instead.
I created a  paver task for it, you can copy from here https://github.com/ponty/paved/blob/master/paved/docs.py
(last function) or easy_install the whole project:

```
easy_install https://github.com/ponty/paved/zipball/master
```

**Pull request merged**
